version: "3"

env:
  BORDER: double
  BORDER_FOREGROUND: "212"
  PADDING: "1 1"
  MARGIN: "1 1"



tasks:
  01-Créer-Helm-Chart:
    desc: "Création d'un helm chart"
    cmds:
      - helm create webapp1-dev
      - helm create webapp1-stag


### environnement development
  02-Installer-helmchart-dev:
    desc: "Installation du Helm chart webapp1-dev avec les valeurs spécifiées"
    cmds:
      - helm install solar-system-dev webapp1-dev/ --values webapp1-dev/values.yaml --namespace development

  03-Mettre-à-jour-helmchart-dev:
    desc: "Mise à jour du Helm chart solar-system avec les nouvelles valeurs"
    cmds:
      - helm upgrade solar-system-dev webapp1-dev/ --values webapp1-dev/values.yaml --namespace development


### environnement staging
  04-Installer-helmchart-stag:
    desc: "Installation du Helm chart webapp1-stag avec les valeurs spécifiées"
    cmds:
      - helm install solar-system-stag webapp1-stag/ --values webapp1-stag/values.yaml --namespace staging

  05-Mettre-à-jour-helmchart-stag:
    desc: "Mise à jour du Helm chart solar-system avec les nouvelles valeurs"
    cmds:
      - helm upgrade solar-system-stag webapp1-stag/ --values webapp1-stag/values.yaml --namespace staging         