version: "3"

env:
  BORDER: double
  BORDER_FOREGROUND: "212"
  PADDING: "1 1"
  MARGIN: "1 1"



tasks:
  01-Créer-Helm-Chart:
    desc: "Création d'un helm chart"
    cmds:
      - helm create shopping-cart-dev
      - helm create shopping-cart-stag


### environnement development
  02-Installer-helmchart-dev:
    desc: "Installation du Helm chart shopping-cart avec les valeurs spécifiées"
    cmds:
      - helm install shopping-cart shopping-cart-dev/ --values shopping-cart-dev/values.yaml --namespace development

  03-Mettre-à-jour-helmchart-dev:
    desc: "Mise à jour du Helm chart shopping-cart avec les nouvelles valeurs"
    cmds:
      - helm upgrade shopping-cart shopping-cart-dev/ --values shopping-cart-dev/values.yaml --namespace development


### environnement staging
  04-Installer-helmchart-stag:
    desc: "Installation du Helm chart shopping-cart avec les valeurs spécifiées"
    cmds:
      - helm install shopping-cart shopping-cart-stag/ --values shopping-cart-stag/values.yaml --namespace staging

  05-Mettre-à-jour-helmchart-stag:
    desc: "Mise à jour du Helm chart shopping-cart avec les nouvelles valeurs"
    cmds:
      - helm upgrade shopping-cart shopping-cart-stag/ --values shopping-cart-stag/values.yaml --namespace staging  




    ### cp -r Helm-frontend/frontend-dev/* Helm-products/products-dev/        