version: "3"

env:
  BORDER: double
  BORDER_FOREGROUND: "212"
  PADDING: "1 1"
  MARGIN: "1 1"



tasks:
  01-Créer-Helm-Chart:
    desc: "Création d'un helm chart"
    cmds:
      - helm create products-dev
      - helm create products-stag


### environnement development
  02-Installer-helmchart-dev:
    desc: "Installation du Helm chart products avec les valeurs spécifiées"
    cmds:
      - helm install products products-dev/ --values products-dev/values.yaml --namespace development

  03-Mettre-à-jour-helmchart-dev:
    desc: "Mise à jour du Helm chart products avec les nouvelles valeurs"
    cmds:
      - helm upgrade products products-dev/ --values products-dev/values.yaml --namespace development


### environnement staging
  04-Installer-helmchart-stag:
    desc: "Installation du Helm chart products avec les valeurs spécifiées"
    cmds:
      - helm install products products-stag/ --values products-stag/values.yaml --namespace staging

  05-Mettre-à-jour-helmchart-stag:
    desc: "Mise à jour du Helm chart products avec les nouvelles valeurs"
    cmds:
      - helm upgrade products products-stag/ --values products-stag/values.yaml --namespace staging  




    ### cp -r Helm-frontend/frontend-dev/* Helm-products/products-dev/        