apiVersion: v1
kind: Service
metadata:
  labels:
    app: products
  name: products
  namespace: development
spec:
  ports:
  - port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: products
  type: NodePort