apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shopping-cart
  name: shopping-cart
  namespace: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopping-cart
  strategy:
    type: RollingUpdate       # Mise à jour continue
    rollingUpdate:
      maxSurge: 1             # Kubernetes autorise l'exécution temporaire de 3 pods maximum (2 anciens pods + 1 nouveau pod)
      maxUnavailable: 1       # vous avez 2 réplicas, au moins 1 pods seront toujours en cours d'exécution pendant que l'un d'eux est mis à jour ou remplacé.
  template:
    metadata:
      labels:
        app: shopping-cart
    spec:
      containers:
      - name: shopping-cart
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
          name: http
          protocol: TCP  
      imagePullSecrets:
      - name: nexus-secret      
