apiVersion: v1
kind: Service
metadata:
  labels:
    app: shopping-cart
  name: shopping-cart
  namespace: development
spec:
  ports:
  - port: 3002
    protocol: TCP
    targetPort: 3002
  selector:
    app: shopping-cart
  type: NodePort