version: "3"

env:
  BORDER: double
  BORDER_FOREGROUND: "212"
  PADDING: "1 1"
  MARGIN: "1 1"



tasks:
  01-Créer-Helm-Chart:
    desc: "Création d'un helm chart"
    cmds:
      - helm create frontend-dev
      - helm create frontend-stag


### environnement development
  02-Installer-helmchart-dev:
    desc: "Installation du Helm chart frontend avec les valeurs spécifiées"
    cmds:
      - helm install frontend frontend-dev/ --values frontend-dev/values.yaml --namespace development

  03-Mettre-à-jour-helmchart-dev:
    desc: "Mise à jour du Helm chart frontend avec les nouvelles valeurs"
    cmds:
      - helm upgrade frontend frontend-dev/ --values frontend-dev/values.yaml --namespace development


### environnement staging
  04-Installer-helmchart-stag:
    desc: "Installation du Helm chart frontend avec les valeurs spécifiées"
    cmds:
      - helm install frontend frontend-stag/ --values frontend-stag/values.yaml --namespace staging

  05-Mettre-à-jour-helmchart-stag:
    desc: "Mise à jour du Helm chart frontend avec les nouvelles valeurs"
    cmds:
      - helm upgrade frontend frontend-stag/ --values frontend-stag/values.yaml --namespace staging         